
package Vistas;

import Tablas.ModelTablePersona;
import clase1conexionbd.Persona;
import clase1conexionbd.controlador.PersonaBD;
import javax.swing.JOptionPane;
import Utilidad.Utilidades;
import clase1conexionbd.Proveedores;
import clase1conexionbd.controlador.ProveedoresBD;
import java.util.ArrayList;
import java.util.List;
import Tablas.ComunicacionVistaModeloTablas;
import Tablas.ModelTableInventario;
import Tablas.ModelTableProveedores;
import clase1conexionbd.Inventario;
import clase1conexionbd.controlador.InventarioBD;
import java.awt.Dialog;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Date;
import java.text.DecimalFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import imagenes.Factura;

public class GestionContable extends javax.swing.JFrame implements ComunicacionVistaModeloTablas {

    private Utilidades utilidades;
    private PersonaBD controladorPersona;
    private Persona personaEditar;

    //creo una variable de tipo persona para hacer uso en los metodos: ELIMINAR, EDITAR
    private Persona persona;
    private GestionPersona gestionPersona;
    //proveedor:
    private Proveedores inventarioEditarLocal;
    private GestionProveedor gestionProveedor;
    private ProveedoresBD controladorProveedor;
    //INVENTARIO
    private Inventario inventarioSeleccionado;
    private GestionInventario gestionInventario;
    private InventarioBD controladorInventario;

    //TABLA: CREACION DE UN OBJETO DE LA CLASE DE LA TABLA:
    private ModelTablePersona ModelTablePersona;
    private ModelTableProveedores ModelTableProveedores;
    private ModelTableInventario ModelTableInventario;

    /**
     * Creates new form GestionPersonaV1
     */
    public GestionContable() {
        controladorPersona = new PersonaBD();
        controladorProveedor = new ProveedoresBD();
        controladorInventario = new InventarioBD();
        //INICIALIZACION DE LA TABLA:
        ModelTablePersona = new ModelTablePersona(controladorPersona.obtenerPersonas(), this);
        ModelTableProveedores = new ModelTableProveedores(controladorProveedor.obtenerProveedores(), this);
        ModelTableInventario = new ModelTableInventario(controladorInventario.obtenerProductosInventario(), this);
        initComponents();

        jrbCedula.setSelected(true);
        utilidades = new Utilidades();
        this.setLocationRelativeTo(null);//CENTRAR VENTANA
        gestionPersona = new GestionPersona(txtcedula, txt_nombre, txt_apellidos, txt_direccion, txt_correo, txt_telefono, utilidades, this, jcmbxGenero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTextField8 = new javax.swing.JTextField();
        tabGeneral = new javax.swing.JTabbedPane();
        panelProveedores = new javax.swing.JPanel();
        txtTituloProveedores = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRazonSocialProveedor = new javax.swing.JTextField();
        txtRucProveedor = new javax.swing.JTextField();
        txtNombreRepresentanteProveedor = new javax.swing.JTextField();
        txtApellidoRepresentanteProveedor = new javax.swing.JTextField();
        txtTipoActividadProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtCorreoProveedor = new javax.swing.JTextField();
        btnGuardarProveedores = new javax.swing.JButton();
        btnEditarProveedores = new javax.swing.JButton();
        btnEliminarProveedores = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ComboParametroBusquedaProveedor = new javax.swing.JComboBox<>();
        txtParametroBusquedaProveedor = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        panelInventario = new javax.swing.JPanel();
        txtTituloInventario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtCantidadProductosInventario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioCompraSinIVA = new javax.swing.JTextField();
        txtDescripcionInventario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoProductoInventario = new javax.swing.JTextField();
        btnGuardarInventario = new javax.swing.JButton();
        btnEditarInventario = new javax.swing.JButton();
        btnEliminarInventario = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPrecioCompraConIVA = new javax.swing.JTextField();
        txtPrecioMayorista = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtClienteFijo = new javax.swing.JTextField();
        txtClienteNormal = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        txtBusquedaInventario = new javax.swing.JTextField();
        ComboBoxInventarioBusqueda = new javax.swing.JComboBox<>();
        btnInventarioBusqueda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        panelClientes = new javax.swing.JPanel();
        CuerpoRegistro = new javax.swing.JPanel();
        jLabel_cedula = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_apellidos = new javax.swing.JLabel();
        jLabel_direccion = new javax.swing.JLabel();
        jLabel_telefono = new javax.swing.JLabel();
        jLabel_correo = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        jButton_BuscarCedula = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_traer = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jcmbxGenero = new javax.swing.JComboBox<>();
        jrbCedula = new javax.swing.JRadioButton();
        jrbPasaporte = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        JDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtTituloClientes = new javax.swing.JLabel();
        tablaClientes = new javax.swing.JScrollPane();
        modelTablePersona = new javax.swing.JTable();
        lbBuscarCliente = new javax.swing.JLabel();
        comboParametrodeBuqueda = new javax.swing.JComboBox<>();
        txtParametroBusqueda = new javax.swing.JTextField();
        btnBuscarPersona = new javax.swing.JButton();
        panelVenta = new javax.swing.JPanel();
        txtTituloVenta = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtcedula_cliente = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_nombre_cliente = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_direccion_cliente = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        txt_telefono_cliente = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        menuGeneral = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenuAccionPersona = new javax.swing.JMenu();
        botonMenuBuscar = new javax.swing.JMenuItem();
        botonMenuGuardar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        botonMenuEliminar = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuAcercade = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jTextField8.setText("jTextField8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION PERSONA");

        panelProveedores.setBackground(new java.awt.Color(60, 179, 221));

        txtTituloProveedores.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtTituloProveedores.setText("GESTION DE PROVEEDORES");

        jPanel1.setBackground(new java.awt.Color(60, 34, 169));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Ruc:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Razón social :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Tipo de Actividad:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nombre Representante Legal:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Apellido Representante Legal:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono:");

        jLabel7.setText("Correo:");

        txtRazonSocialProveedor.setBackground(new java.awt.Color(204, 255, 255));

        txtRucProveedor.setBackground(new java.awt.Color(204, 255, 255));
        txtRucProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucProveedorActionPerformed(evt);
            }
        });

        txtNombreRepresentanteProveedor.setBackground(new java.awt.Color(204, 255, 255));

        txtApellidoRepresentanteProveedor.setBackground(new java.awt.Color(204, 255, 255));

        txtTipoActividadProveedor.setBackground(new java.awt.Color(204, 255, 255));

        txtTelefonoProveedor.setBackground(new java.awt.Color(204, 255, 255));

        txtCorreoProveedor.setBackground(new java.awt.Color(204, 255, 255));

        btnGuardarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardarProveedores.setText("GUARDAR");
        btnGuardarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedoresActionPerformed(evt);
            }
        });

        btnEditarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnEditarProveedores.setText("EDITAR");
        btnEditarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProveedoresActionPerformed(evt);
            }
        });

        btnEliminarProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminarProveedores.setText("ELIMINAR");
        btnEliminarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedoresActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Dirección:");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("Fecha de Registro:");

        txtDireccion.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefonoProveedor)
                    .addComponent(txtCorreoProveedor)
                    .addComponent(txtRazonSocialProveedor)
                    .addComponent(txtTipoActividadProveedor)
                    .addComponent(txtApellidoRepresentanteProveedor)
                    .addComponent(txtNombreRepresentanteProveedor)
                    .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(36, 36, 36)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarProveedores)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnGuardarProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditarProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoActividadProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreRepresentanteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarProveedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtApellidoRepresentanteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProveedores))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tablaProveedores.setBackground(new java.awt.Color(204, 255, 255));
        tablaProveedores.setModel(ModelTableProveedores);
        jScrollPane1.setViewportView(tablaProveedores);

        jLabel8.setText("Buscar Proveedor:");

        ComboParametroBusquedaProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", " " }));
        ComboParametroBusquedaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboParametroBusquedaProveedorActionPerformed(evt);
            }
        });

        txtParametroBusquedaProveedor.setBackground(new java.awt.Color(204, 255, 255));

        btnBuscarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscarProveedor.setText("BUSCAR");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProveedoresLayout.createSequentialGroup()
                        .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProveedoresLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarProveedor))
                            .addGroup(panelProveedoresLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(txtTituloProveedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedoresLayout.createSequentialGroup()
                .addComponent(txtTituloProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParametroBusquedaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabGeneral.addTab("PROVEEDORES", panelProveedores);

        panelInventario.setBackground(new java.awt.Color(60, 170, 227));

        txtTituloInventario.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtTituloInventario.setText("REGISTRO DE INVENTARIO");

        jPanel2.setBackground(new java.awt.Color(60, 0, 208));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Cantidad de Productos:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 12, -1, -1));

        txtCantidadProductosInventario.setBackground(new java.awt.Color(204, 255, 255));
        txtCantidadProductosInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadProductosInventarioKeyTyped(evt);
            }
        });
        jPanel2.add(txtCantidadProductosInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 173, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Precio de compra sin IVA:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 54, -1, -1));

        txtPrecioCompraSinIVA.setBackground(new java.awt.Color(204, 255, 255));
        txtPrecioCompraSinIVA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioCompraSinIVAFocusLost(evt);
            }
        });
        txtPrecioCompraSinIVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioCompraSinIVAKeyPressed(evt);
            }
        });
        jPanel2.add(txtPrecioCompraSinIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 173, -1));

        txtDescripcionInventario.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.add(txtDescripcionInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 160, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Descripción:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 54, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Código de Producto:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 12, -1, -1));

        txtCodigoProductoInventario.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.add(txtCodigoProductoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, -1));

        btnGuardarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardarInventario.setText("GUARDAR");
        btnGuardarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarInventarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        btnEditarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btnEditarInventario.setText("EDITAR");
        btnEditarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarInventarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        btnEliminarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminarInventario.setText("ELIMINAR");
        btnEliminarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInventarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Precio Mayorista:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 126, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Precio de compra incluido IVA:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 90, -1, -1));

        txtPrecioCompraConIVA.setEditable(false);
        txtPrecioCompraConIVA.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.add(txtPrecioCompraConIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 173, -1));

        txtPrecioMayorista.setEditable(false);
        jPanel2.add(txtPrecioMayorista, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 173, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Precio cliente fijo:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 162, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Precio cliente normal:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 198, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Fecha de Caducidad:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 90, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("Fecha de Registro:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 126, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText("Fecha de Actualización:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 162, -1, -1));

        txtClienteFijo.setEditable(false);
        jPanel2.add(txtClienteFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 173, -1));

        txtClienteNormal.setEditable(false);
        jPanel2.add(txtClienteNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 173, -1));

        jDateChooser1.setBackground(new java.awt.Color(204, 255, 255));
        jDateChooser1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, 20));

        jDateChooser2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, 20));

        jDateChooser3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, 20));

        jLabel14.setText("Buscar:");

        txtBusquedaInventario.setBackground(new java.awt.Color(204, 255, 255));

        ComboBoxInventarioBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo Producto", "Descripcion" }));

        btnInventarioBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnInventarioBusqueda.setText("BUSCAR");
        btnInventarioBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioBusquedaActionPerformed(evt);
            }
        });

        tblInventario.setBackground(new java.awt.Color(204, 255, 255));
        tblInventario.setModel(ModelTableInventario);
        jScrollPane2.setViewportView(tblInventario);

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInventarioLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusquedaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInventarioBusqueda)
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(txtTituloInventario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTituloInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ComboBoxInventarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusquedaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventarioBusqueda))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabGeneral.addTab("INVENTARIO", panelInventario);

        panelClientes.setBackground(new java.awt.Color(60, 183, 236));

        CuerpoRegistro.setBackground(new java.awt.Color(60, 14, 179));
        CuerpoRegistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CuerpoRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_cedula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_cedula.setText("DNI");
        CuerpoRegistro.add(jLabel_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jLabel_nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_nombre.setText("Nombre:");
        CuerpoRegistro.add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel_apellidos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_apellidos.setText("Apellidos:");
        CuerpoRegistro.add(jLabel_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel_direccion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_direccion.setText("Dirección:");
        CuerpoRegistro.add(jLabel_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel_telefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_telefono.setText("Teléfono:");
        CuerpoRegistro.add(jLabel_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel_correo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_correo.setText("Correo:");
        CuerpoRegistro.add(jLabel_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtcedula.setBackground(new java.awt.Color(204, 255, 255));
        txtcedula.setToolTipText("Ingrese una cedula valida");
        txtcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedulaFocusLost(evt);
            }
        });
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        CuerpoRegistro.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 270, -1));

        txt_nombre.setBackground(new java.awt.Color(204, 255, 255));
        txt_nombre.setToolTipText("");
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        CuerpoRegistro.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 272, -1));

        txt_apellidos.setBackground(new java.awt.Color(204, 255, 255));
        CuerpoRegistro.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 272, -1));

        txt_direccion.setBackground(new java.awt.Color(204, 255, 255));
        CuerpoRegistro.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 272, -1));

        txt_telefono.setBackground(new java.awt.Color(204, 255, 255));
        txt_telefono.setToolTipText("Ingrese un numero de telefono valido");
        CuerpoRegistro.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 270, -1));

        txt_correo.setBackground(new java.awt.Color(204, 255, 255));
        CuerpoRegistro.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 270, -1));

        jButton_BuscarCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jButton_BuscarCedula.setText("BUSCAR");
        jButton_BuscarCedula.setToolTipText("Buscar persona por cedula");
        jButton_BuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarCedulaActionPerformed(evt);
            }
        });
        CuerpoRegistro.add(jButton_BuscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        CuerpoRegistro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 110, -1));

        btn_traer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/traer (1).png"))); // NOI18N
        btn_traer.setText("TRAER");
        btn_traer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_traerActionPerformed(evt);
            }
        });
        CuerpoRegistro.add(btn_traer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 110, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        CuerpoRegistro.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 110, -1));

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        CuerpoRegistro.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 110, -1));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        CuerpoRegistro.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 110, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Género:");
        CuerpoRegistro.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 58, -1));

        jcmbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No definido", "Hombre ", "Mujer", " " }));
        CuerpoRegistro.add(jcmbxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jrbCedula.setText("ced");
        jrbCedula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbCedulaItemStateChanged(evt);
            }
        });
        CuerpoRegistro.add(jrbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jrbPasaporte.setText("pass");
        jrbPasaporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbPasaporteItemStateChanged(evt);
            }
        });
        CuerpoRegistro.add(jrbPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Fecha de nacimiento:");
        CuerpoRegistro.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        JDateFechaNacimiento.setBackground(new java.awt.Color(204, 255, 255));
        CuerpoRegistro.add(JDateFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 270, -1));

        txtTituloClientes.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtTituloClientes.setText("REGISTRO DE PERSONAS");

        modelTablePersona.setBackground(new java.awt.Color(204, 255, 255));
        modelTablePersona.setModel(ModelTablePersona);
        tablaClientes.setViewportView(modelTablePersona);

        lbBuscarCliente.setText("Buscar Cliente:");

        comboParametrodeBuqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Nombre", "Apellidos", "Telefono", "Correo" }));
        comboParametrodeBuqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboParametrodeBuquedaActionPerformed(evt);
            }
        });

        txtParametroBusqueda.setBackground(new java.awt.Color(204, 255, 255));
        txtParametroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParametroBusquedaActionPerformed(evt);
            }
        });
        txtParametroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtParametroBusquedaKeyReleased(evt);
            }
        });

        btnBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscarPersona.setText("BUSCAR");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(lbBuscarCliente)
                        .addGap(12, 12, 12)
                        .addComponent(comboParametrodeBuqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(txtTituloClientes)))
                .addGap(0, 104, Short.MAX_VALUE))
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(tablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(CuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtTituloClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CuerpoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarCliente)
                    .addComponent(comboParametrodeBuqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        tabGeneral.addTab("CLIENTES", panelClientes);

        txtTituloVenta.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txtTituloVenta.setText("NOTA DE VENTA");

        jLabel25.setText("Número nota de venta:");

        jLabel26.setText("Cédula/RUC cliente:");

        txtcedula_cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedula_clienteFocusLost(evt);
            }
        });

        jLabel27.setText("Nombre cliente:");

        txt_nombre_cliente.setEditable(false);

        jLabel28.setText("Dirección:");

        jLabel29.setText("Teléfono:");

        jLabel30.setText("Fecha venta:");

        txt_direccion_cliente.setEditable(false);

        jTextField5.setEditable(false);

        txt_telefono_cliente.setEditable(false);

        javax.swing.GroupLayout panelVentaLayout = new javax.swing.GroupLayout(panelVenta);
        panelVenta.setLayout(panelVentaLayout);
        panelVentaLayout.setHorizontalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentaLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(txtTituloVenta))
                    .addGroup(panelVentaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29))
                        .addGap(44, 44, 44)
                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcedula_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelVentaLayout.createSequentialGroup()
                                .addComponent(txt_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(txt_direccion_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentaLayout.createSequentialGroup()
                                .addComponent(txt_telefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        panelVentaLayout.setVerticalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtTituloVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtcedula_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(txt_direccion_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_telefono_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addContainerGap(379, Short.MAX_VALUE))
        );

        tabGeneral.addTab("VENTA", panelVenta);

        jRadioButton1.setText("jRadioButton1");

        jMenuArchivo.setText("Archivo");

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(menuSalir);

        jMenuAccionPersona.setText("Accion Persona");

        botonMenuBuscar.setText("Buscar");
        botonMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuBuscarActionPerformed(evt);
            }
        });
        jMenuAccionPersona.add(botonMenuBuscar);

        botonMenuGuardar.setText("Editar");
        botonMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuGuardarActionPerformed(evt);
            }
        });
        jMenuAccionPersona.add(botonMenuGuardar);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuAccionPersona.add(jMenuItem3);

        botonMenuEliminar.setText("Eliminar");
        botonMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuEliminarActionPerformed(evt);
            }
        });
        jMenuAccionPersona.add(botonMenuEliminar);

        jMenuArchivo.add(jMenuAccionPersona);

        menuGeneral.add(jMenuArchivo);

        jMenuEditar.setText("Editar");
        menuGeneral.add(jMenuEditar);

        jMenuAcercade.setText("Acerca de");
        jMenuAcercade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAcercadeMouseClicked(evt);
            }
        });
        menuGeneral.add(jMenuAcercade);

        setJMenuBar(menuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGeneral))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabGeneral)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void buscarPersonaPorCedula() {
        Persona persona = controladorPersona.obtenerPersonCedula(txtcedula.getText());
        if (persona != null) {
            txtcedula.setText(persona.getCedula());
            txt_nombre.setText(persona.getNombre());
            txt_apellidos.setText(persona.getApellido());
            txt_direccion.setText(persona.getDireccion());
            txt_correo.setText(persona.getCorreo());
            txt_telefono.setText(persona.getTelefono());
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO SE ENCONTRO AL USUARIO CON LA CEDULA ESPECIFICADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtcedula.setText(" ");
            txtcedula.requestFocus();
        }

    }

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    public void tablapersona() {
        List<Persona> personasNombre = controladorPersona.obtenerPersonaNombre(txtParametroBusqueda.getText());
        ModelTablePersona.setPersonas(personasNombre);
        ModelTablePersona.fireTableDataChanged();
    }

    private void guardarPersona() {
        if (controladorPersona.obtenerPersonCedula(txtcedula.getText()) != null) {

            JOptionPane.showMessageDialog(rootPane, "La persona con ese número de cédula ya se encuentra registrada en el sistema.");
        } else {
            Persona personaGuardar = gestionPersona.guardarEditar(false);
            if (JDateFechaNacimiento.getDate()!=null) {
                personaGuardar.setFechaNacimiento((Date) JDateFechaNacimiento.getDate());
            }
            if (personaGuardar != null) {
                if (controladorPersona.registrarPersona(personaGuardar)) {
                    JOptionPane.showMessageDialog(rootPane, "PERSONA REGISTRADA CON EXITO");
                    tablapersona();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERROR - NO SE PUEDE AGREGAR A LA PERSONA", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        guardarPersona();

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void editarPersona() {
        controladorPersona.editarPersona(personaEditar);
        if (personaEditar == null) {
            JOptionPane.showMessageDialog(rootPane, "NO HAY UNA PERSONA SELECCIONADA PARA EDITAR");
        }
        Persona personaEditarLocal = gestionPersona.guardarEditar(true);
        if (personaEditarLocal != null) {
            personaEditarLocal.setIdPersona(personaEditar.getIdPersona());
            controladorPersona.editarPersona(personaEditarLocal);
            JOptionPane.showMessageDialog(rootPane, "PERSONA EDITADA CON EXITO");
            personaEditar = null;
            gestionPersona.limpiarCamposPersona();
        }
    }
    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        editarPersona();
        List<Persona> persona = controladorPersona.obtenerPersonas();
        ModelTablePersona.setPersonas(persona);
        ModelTablePersona.fireTableDataChanged();


    }//GEN-LAST:event_btn_editarActionPerformed
    public void eliminarPersona() {
        //ELIMINACION DE PERSONA:
        //CONDICION EN CASO DE QUE LOS CAMPOS ESTEN VACIOS:
        if (txtcedula.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ESPECIFIQUE QUE DESEA ELIMINAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            //CASO CONTRARIO PASA A ELIMINAR LOS DATOS QUE SE ENCUENTREN EN LOS JTXTFIELS:
        } else {
            //MENSAJE DE CONFIRMACION CON SHOW CONFIRM DIALOG CON SI O NO:
            int confirmar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE ELIMINAR A ESTE USUARIO?", "confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //EN CASO DE QUE LA OPCION SEA SI:
            if (confirmar == JOptionPane.YES_OPTION) {
                //CONTROLADOR QUE SE ENCARGARGA DE ELIMINAR:
                controladorPersona.eliminarPersona(personaEditar);
                JOptionPane.showMessageDialog(rootPane, "USUARIO SELECCIONADO ELIMINADO CON EXITO");
                gestionPersona.limpiarCamposPersona();
                tablapersona();

            }
            //EN CASO DE QUE LA OPCION SEA NO:
            if (confirmar == JOptionPane.NO_OPTION) {
                gestionPersona.limpiarCamposPersona();
            }
        }
    }
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        eliminarPersona();

    }//GEN-LAST:event_btn_eliminarActionPerformed


    private void btn_traerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_traerActionPerformed
        List<Persona> ObtenerPersonas = controladorPersona.obtenerPersonas();
        System.out.println("Personas en la base de datos: " + ObtenerPersonas.size());
        personaEditar = ObtenerPersonas.get(ObtenerPersonas.size() - 1);
        System.out.println(personaEditar);
        txtcedula.setText(personaEditar.getCedula());
        txt_nombre.setText(personaEditar.getNombre());
        txt_apellidos.setText(personaEditar.getApellido());
        txt_direccion.setText(personaEditar.getDireccion());
        txt_telefono.setText(personaEditar.getTelefono());
        txt_correo.setText(personaEditar.getCorreo());
        jcmbxGenero.setSelectedIndex(personaEditar.getGenero());
    }//GEN-LAST:event_btn_traerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gestionPersona.limpiarCamposPersona();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_BuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarCedulaActionPerformed
        buscarPersonaPorCedula();
    }//GEN-LAST:event_jButton_BuscarCedulaActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed

    }//GEN-LAST:event_txtcedulaActionPerformed

    private void botonMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuGuardarActionPerformed
        editarPersona();
    }//GEN-LAST:event_botonMenuGuardarActionPerformed

    private void botonMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuBuscarActionPerformed
        buscarPersonaPorCedula();
    }//GEN-LAST:event_botonMenuBuscarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        guardarPersona();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void botonMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuEliminarActionPerformed
        eliminarPersona();
    }//GEN-LAST:event_botonMenuEliminarActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed

        if (comboParametrodeBuqueda.getSelectedItem().equals("Cedula")) {
            List<Persona> personas = new ArrayList<>();
            personas.add(controladorPersona.obtenerPersonCedula(txtParametroBusqueda.getText()));
            ModelTablePersona.setPersonas(personas);
            ModelTablePersona.fireTableDataChanged();

        }
        if (comboParametrodeBuqueda.getSelectedItem().equals("Nombre")) {
            List<Persona> personaNombre = controladorPersona.obtenerPersonaNombre(txtParametroBusqueda.getText());
            ModelTablePersona.setPersonas(personaNombre);
            ModelTablePersona.fireTableDataChanged();

        }
        if (comboParametrodeBuqueda.getSelectedItem().equals("Apellidos")) {
            List<Persona> personaApellidos = controladorPersona.obtenerPersonaApellidos(txtParametroBusqueda.getText());
            ModelTablePersona.setPersonas(personaApellidos);
            ModelTablePersona.fireTableDataChanged();
        }

        if (comboParametrodeBuqueda.getSelectedItem().equals("Telefono")) {
            List<Persona> personaTelefono = controladorPersona.obtenerPersonaTelefono1(txtParametroBusqueda.getText());
            ModelTablePersona.setPersonas(personaTelefono);
            ModelTablePersona.fireTableDataChanged();
        }

        if (comboParametrodeBuqueda.getSelectedItem().equals("Correo")) {
            List<Persona> personaCorreo = controladorPersona.obtenerPersonaCorreo(txtParametroBusqueda.getText());
            ModelTablePersona.setPersonas(personaCorreo);
            ModelTablePersona.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void comboParametrodeBuquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboParametrodeBuquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboParametrodeBuquedaActionPerformed

    private void txtParametroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParametroBusquedaKeyReleased
//AQUIE CODIGO DE TECLEADO RAPIDO
    }//GEN-LAST:event_txtParametroBusquedaKeyReleased

    private void txtParametroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParametroBusquedaActionPerformed

    }//GEN-LAST:event_txtParametroBusquedaActionPerformed

    private void txtRucProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucProveedorActionPerformed

    private void btnGuardarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedoresActionPerformed
        Proveedores proveedores = new Proveedores();
        proveedores.setRuc(txtRucProveedor.getText());
        proveedores.setRazonSocial(txtRazonSocialProveedor.getText());
        proveedores.setTipoActividad(txtTipoActividadProveedor.getText());
        proveedores.setNombreRepresentanteLegal(txtNombreRepresentanteProveedor.getText());
        proveedores.setApellidoRepresentanteLegal(txtApellidoRepresentanteProveedor.getText());
        proveedores.setTelefono(txtTelefonoProveedor.getText());
        proveedores.setCorreo(txtCorreoProveedor.getText());
        if (controladorProveedor.registrarProveedor(proveedores)) {
            JOptionPane.showMessageDialog(rootPane, "PROVEEDOR GUARDADO CON EXITO EN EL SISTEMA");
            limpiarCamposProveedor();
            //ACTUALIZAR TABLA PROVEEDORES:
            ModelTableProveedores.setProveedores(controladorProveedor.obtenerProveedores());
            ModelTableProveedores.fireTableDataChanged();

        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR - NO SE PUEDE AGREGAR AL PROVEEDOR", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarProveedoresActionPerformed

    void limpiarCamposProveedor() {
        txtRucProveedor.setText(" ");
        txtRazonSocialProveedor.setText(" ");
        txtTipoActividadProveedor.setText("");
        txtNombreRepresentanteProveedor.setText("");
        txtApellidoRepresentanteProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtCorreoProveedor.setText("");

    }

    private void editarProveedor() {
        controladorProveedor.editarProveedor(inventarioEditarLocal);
        Proveedores proveedorEditarLocal = gestionProveedor.guardarEditarProveedor();
        if (inventarioEditarLocal != null) {
            inventarioEditarLocal.setIdProveedores(inventarioEditarLocal.getIdProveedores());
            controladorProveedor.editarProveedor(proveedorEditarLocal);
            JOptionPane.showMessageDialog(rootPane, "PERSONA EDITADA CON EXITO");
            inventarioEditarLocal = null;
            limpiarCamposProveedor();
        }
    }
    private void btnEditarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProveedoresActionPerformed
        editarProveedor();
//        List<Proveedores> proveedor = controladorProveedor.obtenerProveedores();
//        ModelTableProveedores.setProveedores(proveedor);
//        ModelTableProveedores.fireTableDataChanged();
    }//GEN-LAST:event_btnEditarProveedoresActionPerformed

    public void tablaProveedores() {
        List<Proveedores> proveedoresNombre = controladorProveedor.obtenerProveedorNombre(txtParametroBusquedaProveedor.getText());
        ModelTableProveedores.setProveedores(proveedoresNombre);
        ModelTableProveedores.fireTableDataChanged();

    }

    public void eliminarProveedor() {
        if (txtRucProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ESPECIFIQUE QUE DESEA ELIMINAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            //CASO CONTRARIO PASA A ELIMINAR LOS DATOS QUE SE ENCUENTREN EN LOS JTXTFIELS:
        } else {
            //MENSAJE DE CONFIRMACION CON SHOW CONFIRM DIALOG CON SI O NO:
            int confirmar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE ELIMINAR A ESTE USUARIO?", "confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //EN CASO DE QUE LA OPCION SEA SI:
            if (confirmar == JOptionPane.YES_OPTION) {
                //CONTROLADOR QUE SE ENCARGARGA DE ELIMINAR:
                controladorProveedor.eliminarProveedor(inventarioEditarLocal);
                JOptionPane.showMessageDialog(rootPane, "USUARIO SELECCIONADO ELIMINADO CON EXITO");
                limpiarCamposProveedor();
                tablaProveedores();

            }
            //EN CASO DE QUE LA OPCION SEA NO:
            if (confirmar == JOptionPane.NO_OPTION) {
                limpiarCamposProveedor();
            }
        }

    }


    private void btnEliminarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedoresActionPerformed
        eliminarProveedor();

    }//GEN-LAST:event_btnEliminarProveedoresActionPerformed

    private void ComboParametroBusquedaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboParametroBusquedaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboParametroBusquedaProveedorActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        if (ComboParametroBusquedaProveedor.getSelectedItem().equals("Nombre")) {
            List<Proveedores> proveedor = new ArrayList<>();
            proveedor.add(controladorProveedor.obtenerProveedoNombre(txtParametroBusquedaProveedor.getText()));
            ModelTableProveedores.setProveedores(proveedor);
            ModelTableProveedores.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed
    public void limpiarCamposInventario() {
        txtCodigoProductoInventario.setText("");
        txtCantidadProductosInventario.setText("");
        txtDescripcionInventario.setText("");
        txtPrecioCompraSinIVA.setText("");
        txtPrecioCompraConIVA.setText("");
        txtPrecioMayorista.setText("");
        txtClienteFijo.setText("");
        txtClienteNormal.setText("");
        

    }

    private void guardarInventario() {
        Inventario inventario = new Inventario();
        inventario.setCodProducto(txtCodigoProductoInventario.getText());
        inventario.setCantProductos(txtCantidadProductosInventario.getText());
        inventario.setDescripcion(txtDescripcionInventario.getText());
        inventario.setPrecioCompraSinIVA(Double.parseDouble(txtPrecioCompraSinIVA.getText()));
        inventario.setPrecioCompraConIVA(Double.parseDouble(txtPrecioCompraConIVA.getText()));
        inventario.setPrecioMayorista(Double.parseDouble(txtPrecioMayorista.getText()));
        inventario.setPrecioClienteFjo(Double.parseDouble(txtClienteFijo.getText()));
        inventario.setPrecioClienteNormal(Double.parseDouble(txtClienteNormal.getText()));
        
        if (controladorInventario.registrarProducto(inventario)) {
            JOptionPane.showMessageDialog(rootPane, "Producto guardado en el sistema");
            limpiarCamposInventario();
            tablaInventario();

        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR - No se guardo el producto", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void tablaInventario() {
        ModelTableInventario.setInventarios(controladorInventario.obtenerProductosInventario());
        ModelTableInventario.fireTableDataChanged();

    }
    private void btnGuardarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInventarioActionPerformed
        guardarInventario();
    }//GEN-LAST:event_btnGuardarInventarioActionPerformed

    private void btnEditarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarInventarioActionPerformed
        if (inventarioSeleccionado == null) {
            JOptionPane.showMessageDialog(rootPane, "NO HAY UN PRODUCTO PARA EDITAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (inventarioSeleccionado != null) {
            inventarioSeleccionado = valoresActualizarInventario(inventarioSeleccionado);
            if (controladorInventario.editarInventario(inventarioSeleccionado)) {
                JOptionPane.showMessageDialog(rootPane, "PRODUCTO EDITADO CON EXITO");
                limpiarCamposInventario();
                inventarioSeleccionado = null;
                tablaInventario();

            } else {
                JOptionPane.showMessageDialog(rootPane, "NO SE PUEDE EDITAR EL PRODUCTO", "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        }

    }//GEN-LAST:event_btnEditarInventarioActionPerformed

    private Inventario valoresActualizarInventario(Inventario i) {
        i.setCodProducto(txtCodigoProductoInventario.getText());
        i.setCantProductos(txtCantidadProductosInventario.getText());
        i.setDescripcion(txtDescripcionInventario.getText());
        i.setPrecioCompraSinIVA(Double.parseDouble(txtPrecioCompraSinIVA.getText()));
        i.setPrecioCompraConIVA(Double.parseDouble(txtPrecioCompraConIVA.getText()));
        i.setPrecioMayorista(Double.parseDouble(txtPrecioMayorista.getText()));
        i.setPrecioClienteFjo(Double.parseDouble(txtClienteFijo.getText()));
        i.setPrecioClienteNormal(Double.parseDouble(txtClienteNormal.getText()));
        return i;
    }


    private void btnEliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInventarioActionPerformed
        if (txtCodigoProductoInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ESPECIFIQUE QUE DESEA ELIMINAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            //CASO CONTRARIO PASA A ELIMINAR LOS DATOS QUE SE ENCUENTREN EN LOS JTXTFIELS:
        } else {
            //MENSAJE DE CONFIRMACION CON SHOW CONFIRM DIALOG CON SI O NO:
            int confirmar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE ELIMINAR A ESTE USUARIO?", "confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //EN CASO DE QUE LA OPCION SEA SI:
            if (confirmar == JOptionPane.YES_OPTION) {
                //CONTROLADOR QUE SE ENCARGARGA DE ELIMINAR:
                controladorInventario.eliminarInventario(inventarioSeleccionado);
                JOptionPane.showMessageDialog(rootPane, "USUARIO SELECCIONADO ELIMINADO CON EXITO");
                inventarioSeleccionado = null;
                limpiarCamposInventario();
                tablaInventario();

            }
            //EN CASO DE QUE LA OPCION SEA NO:
            if (confirmar == JOptionPane.NO_OPTION) {
                limpiarCamposProveedor();
            }
        }

    }//GEN-LAST:event_btnEliminarInventarioActionPerformed

    private void btnInventarioBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioBusquedaActionPerformed
        //METODO QUE HACE LA BUSQUEDA DEPENDIENDO DE LO QUE ELIJA EN EL COMBOBOX                      
        switch (ComboBoxInventarioBusqueda.getSelectedIndex()) {
            case 0://CODIGO
                //CODIGO COPIADO DE METODO TABLA, ESTO SIRVE PARA ACTUALIZAR LA TABLA CUANDO SE BUSCA ALGO EN EL MOMENTO
                ModelTableInventario.setInventarios(controladorInventario.obtenerProductosInventarioCodigo(txtBusquedaInventario.getText()));
                ModelTableInventario.fireTableDataChanged();
                break;
            case 1://DESCRIPCION
                ModelTableInventario.setInventarios(controladorInventario.obtenerProductosInventarioDescripcion(txtBusquedaInventario.getText()));
                ModelTableInventario.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnInventarioBusquedaActionPerformed
    //METODOS DE EJEMPLOS - EXPOSICION:
    private void txtPrecioCompraSinIVAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraSinIVAKeyPressed
        //1. KEYPRESSED - VERIFICA INGRESO DE DATOS NUMERICOS NO LETRAS:
    }//GEN-LAST:event_txtPrecioCompraSinIVAKeyPressed

    private void txtCantidadProductosInventarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadProductosInventarioKeyTyped
        //3. KEYTYPED: CADA QUE PRESIONE EL BOTON ESPACIO NO TE DEJARA
        char car = evt.getKeyChar();
        if (car == KeyEvent.VK_SPACE) {
            JOptionPane.showMessageDialog(rootPane, "NO PUEDE DAR ESPACIOS");
            txtCantidadProductosInventario.setText("");
        }
    }//GEN-LAST:event_txtCantidadProductosInventarioKeyTyped

    private void txtcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusLost
        if (jrbCedula.isSelected()) {
            if (!utilidades.validadorDeCedula(txtcedula.getText())) {
                JOptionPane.showMessageDialog(rootPane, "LA CEDULA INGRESADA ES INCORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            //VERIFICA SI YA ESTA O NO LA CEDULA REGISTRADA:
            if (controladorPersona.obtenerPersonCedula(txtcedula.getText()) != null) {
                JOptionPane.showMessageDialog(rootPane, "LA PERSONA INGRESADA CON ESTA CEDULA YA SE ENCUENTRA REGISTRADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (jrbPasaporte.isSelected()) {
            if (txtcedula.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "LA CEDULA INGRESADA ES INCORRECTA", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtcedula.requestFocus();//SIRVE PARA UBICAR EL CURSOR EN UN CAMPO VACIO

            }
        }

    }//GEN-LAST:event_txtcedulaFocusLost
    private void Operaciones() {
        double PrecioConIva;
        double PrecioClienteFijo;
        double PrecioClienteNormal;
        double PrecioMayorista;
        
     
        PrecioConIva = Double.parseDouble(txtPrecioCompraSinIVA.getText()) * 0.12 + Double.parseDouble(txtPrecioCompraSinIVA.getText());
        String Preciobase = String.valueOf(PrecioConIva);
        BigDecimal a= new BigDecimal(Preciobase);
        a= a.setScale(2, RoundingMode.HALF_UP);
        txtPrecioCompraConIVA.setText(a.toString());
        
        PrecioMayorista = (PrecioConIva * 0.10) + PrecioConIva;
        String precioMayorista = String.valueOf(PrecioMayorista);
        BigDecimal bd1 = new BigDecimal(precioMayorista);
        bd1 = bd1.setScale(2, RoundingMode.HALF_UP);
        txtPrecioMayorista.setText(bd1.toString());

        PrecioClienteFijo = (PrecioConIva * 0.12) + PrecioConIva;
        String precioClienteFijo = String.valueOf(PrecioClienteFijo);
        BigDecimal bd2 = new BigDecimal(precioClienteFijo);
        bd2 = bd2.setScale(2, RoundingMode.HALF_UP);
        txtClienteFijo.setText(bd2.toString());

        PrecioClienteNormal = (PrecioConIva * 0.15) + PrecioConIva;
        String precioClienteNormal = String.valueOf(PrecioClienteNormal);
        BigDecimal bd3 = new BigDecimal(precioClienteNormal);
        bd3 = bd3.setScale(2, RoundingMode.HALF_UP);
        txtClienteNormal.setText(bd3.toString());
    }


    private void jrbCedulaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbCedulaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jrbPasaporte.setSelected(false);
        }
    }//GEN-LAST:event_jrbCedulaItemStateChanged

    private void jrbPasaporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbPasaporteItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jrbCedula.setSelected(false);
        }
    }//GEN-LAST:event_jrbPasaporteItemStateChanged

    private void jMenuAcercadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAcercadeMouseClicked
        Factura pantallaAcercaDe = new Factura(this, true);
        pantallaAcercaDe.setVisible(true);
    }//GEN-LAST:event_jMenuAcercadeMouseClicked

    private void txtPrecioCompraSinIVAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioCompraSinIVAFocusLost

        Operaciones();
    }//GEN-LAST:event_txtPrecioCompraSinIVAFocusLost

    private void txtcedula_clienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedula_clienteFocusLost

    Persona persona = controladorPersona.obtenerPersonCedula(txtcedula_cliente.getText());
        if (persona != null) {
            txtcedula.setText(persona.getCedula());
            txt_nombre_cliente.setText(persona.getNombre());
            txt_telefono_cliente.setText(persona.getTelefono());
            txt_direccion_cliente.setText(persona.getDireccion());
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "NO SE ENCONTRO AL USUARIO CON LA CEDULA ESPECIFICADA", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtcedula_cliente.setText(" ");
            txtcedula_cliente.requestFocus();
        }
        
    }//GEN-LAST:event_txtcedula_clienteFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionContable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxInventarioBusqueda;
    private javax.swing.JComboBox<String> ComboParametroBusquedaProveedor;
    private javax.swing.JPanel CuerpoRegistro;
    private com.toedter.calendar.JDateChooser JDateFechaNacimiento;
    private javax.swing.JMenuItem botonMenuBuscar;
    private javax.swing.JMenuItem botonMenuEliminar;
    private javax.swing.JMenuItem botonMenuGuardar;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnEditarInventario;
    private javax.swing.JButton btnEditarProveedores;
    private javax.swing.JButton btnEliminarInventario;
    private javax.swing.JButton btnEliminarProveedores;
    private javax.swing.JButton btnGuardarInventario;
    private javax.swing.JButton btnGuardarProveedores;
    private javax.swing.JButton btnInventarioBusqueda;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_traer;
    private javax.swing.JComboBox<String> comboParametrodeBuqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_BuscarCedula;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_apellidos;
    private javax.swing.JLabel jLabel_cedula;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAccionPersona;
    private javax.swing.JMenu jMenuAcercade;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JComboBox<String> jcmbxGenero;
    private javax.swing.JRadioButton jrbCedula;
    private javax.swing.JRadioButton jrbPasaporte;
    private javax.swing.JLabel lbBuscarCliente;
    private javax.swing.JMenuBar menuGeneral;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JTable modelTablePersona;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JTabbedPane tabGeneral;
    private javax.swing.JScrollPane tablaClientes;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtApellidoRepresentanteProveedor;
    private javax.swing.JTextField txtBusquedaInventario;
    private javax.swing.JTextField txtCantidadProductosInventario;
    private javax.swing.JTextField txtClienteFijo;
    private javax.swing.JTextField txtClienteNormal;
    private javax.swing.JTextField txtCodigoProductoInventario;
    private javax.swing.JTextField txtCorreoProveedor;
    private javax.swing.JTextField txtDescripcionInventario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreRepresentanteProveedor;
    private javax.swing.JTextField txtParametroBusqueda;
    private javax.swing.JTextField txtParametroBusquedaProveedor;
    private javax.swing.JTextField txtPrecioCompraConIVA;
    private javax.swing.JTextField txtPrecioCompraSinIVA;
    private javax.swing.JTextField txtPrecioMayorista;
    private javax.swing.JTextField txtRazonSocialProveedor;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtTelefonoProveedor;
    private javax.swing.JTextField txtTipoActividadProveedor;
    private javax.swing.JLabel txtTituloClientes;
    private javax.swing.JLabel txtTituloInventario;
    private javax.swing.JLabel txtTituloProveedores;
    private javax.swing.JLabel txtTituloVenta;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_direccion_cliente;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre_cliente;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_telefono_cliente;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcedula_cliente;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickPersona(Persona p) {
        //System.out.println("Persona " + p.toString());
        txtcedula.setText(p.getCedula());
        txt_nombre.setText(p.getNombre());
        txt_apellidos.setText(p.getApellido());
        txt_direccion.setText(p.getDireccion());
        txt_correo.setText(p.getCorreo());
        txt_telefono.setText(p.getTelefono());
        JDateFechaNacimiento.setDate(p.getFechaNacimiento());
        personaEditar = p;
        persona = p;

    }

    @Override
    public void clickProveedores(Proveedores p) {
        txtRucProveedor.setText(p.getRuc());
        txtRazonSocialProveedor.setText(p.getRazonSocial());
        txtTipoActividadProveedor.setText(p.getTipoActividad());
        txtNombreRepresentanteProveedor.setText(p.getNombreRepresentanteLegal());
        txtApellidoRepresentanteProveedor.setText(p.getApellidoRepresentanteLegal());
        txtTelefonoProveedor.setText(p.getTelefono());
        txtCorreoProveedor.setText(p.getCorreo());
        inventarioEditarLocal = p;

    }

    @Override
    public void clickInventario(Inventario i) {
        inventarioSeleccionado = i;
        txtCodigoProductoInventario.setText(i.getCodProducto());
        txtDescripcionInventario.setText(i.getDescripcion());
//        txtPrecioCompraSinIVA.setText(i.getPrecioCompra());
//        txtPrecioVentaInventario.setText(i.getPrecioVenta());
        txtCantidadProductosInventario.setText(i.getCantProductos());

    }

}
